修改riskDetector的字符串拼接方式
GWmodel-Lab/OGE-GWmodel-InternalDevelop pull request #49
Opened 2024-01-04 08:57 UTC by WenNianshuo

cn_aging有的属性分层比较多，导致字符串太长，之前没有出结果是因为一直在拼接字符串。
修改了字符串的拼接方式。

2024-01-04 10:02 UTC, RoryuOu requested changes
自己跑一遍
println(Geodetector.riskDetector(shpfile, "aging", "PCGDP,GI,FD,education"))

2024-01-05 06:41 UTC, RoryuOu reviewed
如果你的输出就给人看这个，我就把它同步到那边的仓库去

2024-01-05 14:17 UTC, RoryuOu commented
改完了建议自己测试一下。
println(Geodetector.riskDetector(shpfile, "aging", "GI"))

2024-01-05 14:34 UTC, WenNianshuo commented
加的代码内容是检测到某个自变量分层太多就抛出异常，这行代码跑的是对的
println(Geodetector.riskDetector(shpfile, "aging", "GI"))
The number of strata in GI is 286. The data should be dispersed.

2024-01-08 12:34 UTC, RoryuOu approved these changes

2024-01-08 12:34 UTC, merged